# Generated by Django 5.0.3 on 2024-03-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(max_length=100)),
                ("Industry", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=250)),
                ("Field", models.CharField(max_length=100)),
                (
                    "Pronouns",
                    models.CharField(
                        choices=[("H", "He"), ("S", "She"), ("O", "Other")],
                        default="O",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
