# Generated by Django 4.1 on 2024-03-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('approx_completion_date', models.DateField()),
                ('description', models.CharField(max_length=2000)),
                ('collab_type', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid'), ('C', 'Collaboration')], default='Collaboration', max_length=15)),
                ('sample_work', models.CharField(max_length=1000)),
                ('role_count', models.IntegerField()),
                ('mode', models.CharField(choices=[('I', 'In-person'), ('V', 'Virtual'), ('H', 'Hybrid')], default='Hybrid', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='client',
            name='sample_work',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='creator',
            name='sample_work',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
