# Generated by Django 5.0.3 on 2024-03-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creator",
            old_name="Pronouns",
            new_name="pronoun",
        ),
        migrations.RemoveField(
            model_name="client",
            name="Industry",
        ),
        migrations.RemoveField(
            model_name="creator",
            name="Field",
        ),
        migrations.AddField(
            model_name="client",
            name="industry",
            field=models.CharField(
                choices=[("arts", "ARTS"), ("music", "MUSIC"), ("acting", "ACTING")],
                default="arts",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="field",
            field=models.CharField(
                choices=[("arts", "ARTS"), ("music", "MUSIC"), ("acting", "ACTING")],
                default="arts",
                max_length=10,
            ),
        ),
    ]
