# Generated by Django 5.0.3 on 2024-04-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passionuser',
            name='sample_work',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sample_work', to='app1.usersampleworktable'),
        ),
    ]
