# Generated by Django 5.0.3 on 2024-04-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="creator",
            options={"verbose_name": "Creator", "verbose_name_plural": "Creators"},
        ),
        migrations.RemoveField(
            model_name="project",
            name="role_count",
        ),
        migrations.AlterField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant",
                to="app1.creator",
            ),
        ),
    ]
