# Generated by Django 5.0.3 on 2024-04-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_samplewrktbl_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="other_status",
        ),
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
        migrations.AlterField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="app1.creator",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="app1.role",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("L", "Live"),
                    ("MS", "MatchSuccess"),
                    ("NM", "NoMatches"),
                    ("C", "Complete"),
                ],
                default=None,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="app1.project",
            ),
        ),
    ]
