# Generated by Django 4.1 on 2024-03-19 12:13

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_project_remove_client_address_remove_creator_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='creator',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='creator',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.IntegerField(help_text='Enter a 10-digit phone number', null=True, validators=[app1.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='client',
            name='org_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='sample_work',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='creator',
            name='email',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='creator',
            name='field',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='creator',
            name='mobile',
            field=models.IntegerField(help_text='Enter a 10-digit phone number', null=True, validators=[app1.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='creator',
            name='sample_work',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
